### ISSUE TITLE
Add volunteers testimonies 

### ISSUE THREAD

**Issue by tiphaineboyer** [oviohub/website#33]
We now have 3 quotes we can use and display on the website Volunteer Page:

"I was looking for an opportunity to give back and join a community of folks willing to do the same while leveraging my experience. I was immediately excited about Ovio because it helped me find the right opportunity for me right away! They matched me with a project that aligns with my technical expertise, delivering values on things that I find important." Tyler - AWS

"I want to use my skills to give back to communities and help people. I also want to use this opportunity to keep sharp on some skills that my current job doesn't require. Ovio is the solution for me" Marcus - AWS

"Ovio and skill-based volunteering, in general, is the best way to volunteer!" Ignacio - Salesforce

"Thank you so much for connecting me with this resource. I wouldn't have stuck with it to find this if Ovio weren't so engaged with volunteers like me." Olivia - American Express

If @ericboucher you have more add them here.

**Comment by mamadOuologuem** [comment]
[react-visibility-sensor](https://github.com/joshwnj/react-visibility-sensor) can be usefull for animation
