### ISSUE TITLE
Screenshots on Developer and Company pages not displayed correctly with safari

### ISSUE THREAD

**Issue by tiphaineboyer** [oviohub/website#65]
Opening the website with Safari made the images on both the companies and the developers pages look as below.
<img width="1424" alt="Screen Shot 2020-06-02 at 6 04 21 PM" src="https://user-images.githubusercontent.com/38056877/83584280-7f6fc780-a4fb-11ea-9f69-5c1ccff01dc8.png">

**Comment by ericboucher** [comment]
10:4
